# Generated by Django 4.2.5 on 2023-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_post_delete_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
